services:
  sc2-server:
    image: pysc2
    container_name: sc2-server
    command: >
      bash -c "python /root/launch_sc2.py &
               python /root/display_frames.py;
               wait"
    environment:
      - DISPLAY=${DISPLAY}
      - LIBGL_ALWAYS_SOFTWARE=1
      - SDL_VIDEO_X11_MITSHM=0
      - SC2PATH=/root/StarCraftII/
      - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XAUTHORITY}:/root/.Xauthority:rw
      - ./maps/InterloperTest.SC2Map:/root/StarCraftII/Maps/InterloperTest.SC2Map:ro
      - ./sc2_server/launch_sc2.py:/root/launch_sc2.py:ro
      - ./sc2_server/play_sc2.py:/root/play_sc2.py:ro
      - ./sc2_server/display_frames.py:/root/display_frames.py:ro
      - ./sc2-signals:/tmp/sc2-signals
    expose:
      - "8167"
    ports:
      - "8167:8167"
    networks:
      - sc2net
    restart: unless-stopped

  ros2-bridge:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: ros
        USER_UID: ${UID:-1000}
        USER_GID: ${GID:-1000}
    image: sc2-bridge-dev
    container_name: sc2-bridge
    depends_on:
      - sc2-server
    environment:
      - SC2_HOST=sc2-server
      - SC2_PORT=8167
      - SC2_MAP=/root/StarCraftII/Maps/InterloperTest.SC2Map
    volumes:
      - .:/home/ros/ws
      - ./sc2-signals:/tmp/sc2-signals
    working_dir: /home/ros/ws/ros2_ws
    command: >
      bash -lc "colcon build --symlink-install &&
      source install/setup.bash &&
      ros2 launch sc2_bridge sc2_bridge.launch.py"
    networks:
      - sc2net

networks:
  sc2net:
    driver: bridge
